# Generated by Django 3.0.3 on 2020-02-27 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200227_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('C', 'Customer'), ('D', 'Driver'), ('G', 'Guide')], default='C', max_length=1)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('number', models.PositiveSmallIntegerField()),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('econ_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Emergency Contact Name')),
                ('econ_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Emergency Contact Number')),
                ('license', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
