# Generated by Django 3.0.3 on 2020-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiletry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('C', 'Customer'), ('E', 'Employee')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='econ_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Emergency Contact Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
