# Generated by Django 3.0.3 on 2020-02-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('img', models.ImageField(default='def_site.jpg', upload_to='site_pics')),
                ('number', models.PositiveSmallIntegerField()),
                ('rating', models.FloatField(default=3.0)),
                ('category', models.CharField(choices=[('C1', 'Category 1'), ('C2', 'Category 2')], default='C1', max_length=2)),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=25)),
                ('o_time', models.TimeField()),
                ('c_time', models.TimeField()),
            ],
        ),
    ]
