# Generated by Django 3.0.3 on 2020-09-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customer_username'),
        ('Sites', '0003_auto_20200912_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pickloc', models.TextField()),
                ('droploc', models.TextField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('I', 'In Progress')], default='M', max_length=1)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CX', to='users.Customer')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EMP', to='users.Customer')),
                ('Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sites.Site')),
            ],
        ),
    ]
