# Generated by Django 3.0.3 on 2020-09-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Site',
            new_name='site',
        ),
    ]
