# Generated by Django 3.0.3 on 2020-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0005_auto_20200912_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Confirmation'), ('B', 'Booked'), ('C', 'Cancelled'), ('I', 'In Progress')], default='B', max_length=1),
        ),
    ]
