# Generated by Django 3.0.3 on 2020-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0006_auto_20200912_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Confirmation'), ('B', 'Booked'), ('I', 'In Progress'), ('C', 'Completed'), ('R', 'Removed')], default='B', max_length=1),
        ),
    ]
