# Generated by Django 3.0.3 on 2020-09-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sites', '0005_auto_20200912_1658'),
        ('users', '0007_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('rating', models.SmallIntegerField()),
                ('report', models.CharField(choices=[('R1', 'Report 1'), ('R2', 'Report 2'), ('R3', 'Report 3'), ('R4', 'Report 4'), ('R5', 'Report 5')], default='R1', max_length=2)),
                ('valid', models.CharField(choices=[('V', 'Valid'), ('D', 'Deleted'), ('S', 'Spam')], default='V', max_length=1)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sites.Booking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RE', to='users.Customer')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RR', to='users.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Site_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('rating', models.SmallIntegerField()),
                ('report', models.CharField(choices=[('R1', 'Report 1'), ('R2', 'Report 2'), ('R3', 'Report 3'), ('R4', 'Report 4'), ('R5', 'Report 5')], default='R1', max_length=2)),
                ('valid', models.CharField(choices=[('V', 'Valid'), ('D', 'Deleted'), ('S', 'Spam')], default='V', max_length=1)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sites.Booking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sites.Site')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
    ]
