# Generated by Django 3.0.3 on 2020-09-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_feedback',
            name='title',
            field=models.CharField(default='Review Title', max_length=25),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='report',
            field=models.CharField(choices=[('R1', 'None'), ('R2', 'Report 2'), ('R3', 'Report 3'), ('R4', 'Report 4'), ('R5', 'Report 5')], default='R1', max_length=2),
        ),
    ]
