# Generated by Django 3.0.3 on 2020-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200912_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_feedback',
            name='booking',
        ),
        migrations.AlterField(
            model_name='site_feedback',
            name='report',
            field=models.CharField(choices=[('R1', 'None'), ('R2', 'Report 2'), ('R3', 'Report 3'), ('R4', 'Report 4'), ('R5', 'Report 5')], default='R1', max_length=2),
        ),
        migrations.DeleteModel(
            name='User_Feedback',
        ),
    ]
