# Generated by Django 3.0.3 on 2020-09-13 13:24

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0008_auto_20200913_1854'),
        ('users', '0008_auto_20200913_1854'),
        ('feedback', '0003_auto_20200913_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_feedback',
            name='rating',
            field=models.SmallIntegerField(validators=[feedback.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='site_feedback',
            name='report',
            field=models.CharField(choices=[('R1', 'None'), ('R2', 'Site was not as advertised'), ('R3', 'Site location was incorrect'), ('R4', 'Site was too crowded'), ('R5', 'Pick up/Drop Time was delayed'), ('R6', 'Employee behaved inappropriately'), ('R7', 'Other (Elaborate in Report Content)')], default='R1', max_length=2),
        ),
        migrations.AlterField(
            model_name='site_feedback',
            name='reviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sites.Site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='site_feedback',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='User'),
        ),
    ]
